version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: cc_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ccdb
      MYSQL_USER: ccuser
      MYSQL_PASSWORD: devpass
      MYSQL_ROOT_PASSWORD: rootpass
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./CC_BE
      dockerfile: Dockerfile
    container_name: cc_backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ccdb
      MYSQL_USER: ccuser
      MYSQL_PASSWORD: devpass
    ports:
      - "8080:8080"

#  frontend:
#    build:
#      context: ./CC_FE
#      dockerfile: Dockerfile
#    container_name: cc_frontend
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
    # 환경변수/볼륨 등은 FE Dockerfile 완성 후 추가 예정
    # depends_on:
    #   - backend

volumes:
  mysql_data:
